# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20170125_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
