# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='review',
            new_name='reviews',
        ),
    ]
