# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20170125_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviews',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
    ]
