# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20170125_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviews',
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.ForeignKey(default='review', on_delete=django.db.models.deletion.CASCADE, to='reviews.Review'),
            preserve_default=False,
        ),
    ]
