# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20170125_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=1000),
        ),
    ]
